import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';

export class GitHubUtils {
    public static async initRepo(workspaceRoot: string): Promise<void> {
        const terminal = vscode.window.createTerminal('🐙 Git Init');
        terminal.show();
        terminal.sendText(`cd "${workspaceRoot}"`);
        terminal.sendText('git init');
        terminal.sendText('git add .');
        terminal.sendText('git commit -m "Initial commit by Project Starter"');

        vscode.window.showInformationMessage('Git repository initialized and initial commit created!');
    }

    public static async generateBoilerplate(workspaceRoot: string): Promise<void> {
        // Generate .gitignore
        const gitignorePath = path.join(workspaceRoot, '.gitignore');
        if (!fs.existsSync(gitignorePath)) {
            const gitignoreContent = `# Dependency directories
node_modules/
jspm_packages/

# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Runtime data
pids
*.pid
*.seed
*.pid.lock

# Directory for instrumented libs generated by jscoverage/JSCover
lib-cov

# Coverage directory used by tools like istanbul
coverage

# nyc dev tool
.nyc_output

# Grunt intermediate storage (http://gruntjs.com/creating-plugins#storing-task-files)
.grunt

# Bower dependency directory (https://bower.io/)
bower_components

# node-waf configuration
.lock-wscript

# Compiled binary addons (https://nodejs.org/api/addons.html)
build/Release

# Dependency directories
node_modules/
jspm_packages/

# TypeScript v1.x command line compiler cache
# (Not needed for v2.0+ but still used by some tools)
atp-cache.json

# Optional npm cache directory
.npm

# Optional eslint cache
.eslintcache

# Optional REPL history
.node_repl_history

# Output of 'npm pack'
*.tgz

# Yarn Integrity file
.yarn-integrity

# dotenv environment variable files
.env
.env.test
.env.production

# next.js build output
.next/
`;
            fs.writeFileSync(gitignorePath, gitignoreContent);
            vscode.window.showInformationMessage('Successfully generated .gitignore');
        }

        // Generate README.md
        const readmePath = path.join(workspaceRoot, 'README.md');
        if (!fs.existsSync(readmePath)) {
            const readmeContent = `# Project Started with Project Starter 🚀

This project was scaffolded and configured using the [Project Starter](https://github.com/your-repo/project-starter) VS Code extension.

## Getting Started

1.  **Install Dependencies:** Run \`npm install\` in both frontend and backend directories.
2.  **Environment Variables:** Configure your \`.env\` files using the Project Starter Dashboard.
3.  **Start Servers:** Use the "Start Servers" button in the extension dashboard or run the generated VS Code tasks.

## Features Integrated

-   Auto-detected frameworks
-   Port conflict detection
-   Unified logging
-   Docker support (if enabled)
-   Health monitoring
`;
            fs.writeFileSync(readmePath, readmeContent);
            vscode.window.showInformationMessage('Successfully generated README.md');
        }
    }
}
